### ISSUE TITLE
Uploaded hero images delete themselves 

### ISSUE THREAD

**Issue by druliner** [uw-drupal/uw_drupal_theme#13]
Uploaded hero images are set as temporary files and are automatically deleted when admin/config/media/file-system are set to Delete temporary files.

When testing you view and shorten the delete interval to one minute with: 
  drush @this.travel config:set system.file temporary_maximum_age 60
and then run:
  drush cron

**Comment by akrikawauw** [comment]
Thanks, Dan. I just pushed [bugfix/hero-image-files](https://github.com/uw-drupal/uw_drupal_theme/tree/bugfix/hero-image-files) with changes to uw_drupal_theme.theme that should flag the files as permanent. Can you test it out?

**Comment by druliner** [comment]
Yeah, I’ll try and spin it up this afternoon.
dd

**Comment by druliner** [comment]
Pulled down the branch and confirmed it works. Thanks!
